class Problem2

=begin
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
=end

  def generate_fibonacci_sequence(max_value)
    sequence = [1, 2]
    (1..Float::INFINITY).each do
      next_value = sequence.last(2).reduce(:+)
      break if next_value > max_value
      sequence << next_value
    end
    sequence
  end

  def sum_of_even_values(array)
    array.select { |n| n.even? }.reduce(:+)
  end

end
