require_relative '../lib/problem_1'
require_relative '../lib/problem_2'
require_relative '../lib/problem_3'
require_relative '../lib/problem_4'
require_relative '../lib/problem_5'
require_relative '../lib/problem_7'
require_relative '../lib/problem_25'
