class Problem2

=begin
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
=end

  def self.fibonacci_sequence_generator (number)
    sequence = [1,2]
    (1..number).each {
      break unless sequence[-1] + sequence[-2] < number
      sequence << sequence[-1] + sequence[-2]}
    sequence
  end

  def self.sum_of_even_fibonacci_sequence_values (sequence)
    sum = 0
    sequence.to_a.each { |n| sum += n if n % 2 == 0 }
    sum
  end

  fibonacci_sequence = self.fibonacci_sequence_generator 4000000
  sum = self.sum_of_even_fibonacci_sequence_values fibonacci_sequence
  puts "sum is: #{sum}"

end